import { t, type Dictionary } from "intlayer";

const addSeekerModalContent = {
  key: "addSeekerModal",
  content: {
    addSeeker: t({
      ru: "Добавить соискателя",
      en: "Add job seeker",
      he: "הוסף מחפש עבודה",
      ar: "أضف باحث عن عمل",
      uk: "Додати шукача роботи",
    }),
    languageRussian: t({
      ru: "Русский",
      en: "Russian",
      he: "רוסית",
      ar: "الروسية",
      uk: "Російська",
    }),
    languageArabic: t({
      ru: "Арабский",
      en: "Arabic",
      he: "ערבית",
      ar: "العربية",
      uk: "Арабська",
    }),
    languageEnglish: t({
      ru: "Английский",
      en: "English",
      he: "אנגלית",
      ar: "الإنجليزية",
      uk: "Англійська",
    }),
    languageHebrew: t({
      ru: "Иврит",
      en: "Hebrew",
      he: "עברית",
      ar: "العبرية",
      uk: "Іврит",
    }),
    employmentFull: t({
      ru: "Полная занятость",
      en: "Full-time",
      he: "משרה מלאה",
      ar: "دوام كامل",
      uk: "Повна зайнятість",
    }),
    employmentPartial: t({
      ru: "Частичная занятость",
      en: "Part-time",
      he: "משרה חלקית",
      ar: "دوام جزئي",
      uk: "Часткова зайнятість",
    }),
    documentVisaB1: t({
      ru: "Виза Б1",
      en: "B1 Visa",
      he: "ויזה B1",
      ar: "تأشيرة B1",
      uk: "Віза Б1",
    }),
    documentVisaB2: t({
      ru: "Виза Б2",
      en: "B2 Visa",
      he: "ויזה B2",
      ar: "تأشيرة B2",
      uk: "Віза Б2",
    }),
    documentTeudatZehut: t({
      ru: "Теудат Зеут",
      en: "Teudat Zehut",
      he: "תעודת זהות",
      ar: "هوية شخصية",
      uk: "Теудат Зеут",
    }),
    documentWorkVisa: t({
      ru: "Рабочая виза",
      en: "Work visa",
      he: "ויזה לעבודה",
      ar: "تأشيرة عمل",
      uk: "Робоча віза",
    }),
    documentOther: t({
      ru: "Другое",
      en: "Other",
      he: "אחר",
      ar: "أخرى",
      uk: "Інше",
    }),
    fillAllFieldsError: t({
      ru: "Пожалуйста, заполните все обязательные поля",
      en: "Please fill in all required fields",
      he: "אנא מלא את כל השדות הנדרשים",
      ar: "يرجى ملء جميع الحقول المطلوبة",
      uk: "Будь ласка, заповніть всі обов'язкові поля",
    }),
    languageSelectionError: t({
      ru: "Пожалуйста, выберите языки и родной язык",
      en: "Please select languages and native language",
      he: "אנא בחר שפות ושפת אם",
      ar: "يرجى اختيار اللغات واللغة الأم",
      uk: "Будь ласка, оберіть мови та рідну мову",
    }),
    locationPlaceholder: t({
      ru: "Выберите город",
      en: "Select city",
      he: "בחר עיר",
      ar: "اختر المدينة",
      uk: "Оберіть місто",
    }),
    briefDescriptionPlaceholder: t({
      ru: "Краткое описание",
      en: "Brief description",
      he: "תיאור קצר",
      ar: "وصف مختصر",
      uk: "Короткий опис",
    }),
    genderMale: t({
      ru: "Мужчина",
      en: "Male",
      he: "זכר",
      ar: "ذكر",
      uk: "Чоловік",
    }),
    genderFemale: t({
      ru: "Женщина",
      en: "Female",
      he: "נקבה",
      ar: "أنثى",
      uk: "Жінка",
    }),
    demanded: t({
      ru: "Востребованный кандидат",
      en: "In-demand candidate",
      he: "מועמד מבוקש",
      ar: "مرشح مطلوب",
      uk: "Затребуваний кандидат",
    }),
    nextButton: t({
      ru: "Далее",
      en: "Next",
      he: "הבא",
      ar: "التالي",
      uk: "Далі",
    }),
    categoryPlaceholder: t({
      ru: "Выберите категорию",
      en: "Select category",
      he: "בחר קטגוריה",
      ar: "اختر الفئة",
      uk: "Оберіть категорію",
    }),
    employmentTypePlaceholder: t({
      ru: "Тип занятости",
      en: "Employment type",
      he: "סוג תעסוקה",
      ar: "نوع التوظيف",
      uk: "Тип зайнятості",
    }),
    documentTypePlaceholder: t({
      ru: "Тип документа",
      en: "Document type",
      he: "סוג מסמך",
      ar: "نوع المستند",
      uk: "Тип документа",
    }),
    backButton: t({
      ru: "Назад",
      en: "Back",
      he: "חזור",
      ar: "رجوع",
      uk: "Назад",
    }),
    saveButton: t({
      ru: "Сохранить",
      en: "Save",
      he: "שמור",
      ar: "حفظ",
      uk: "Зберегти",
    }),
    namePlaceholder: t({
      ru: "Имя",
      en: "Name",
      he: "שם",
      ar: "الاسم",
      uk: "Ім'я",
    }),
    phonePlaceholder: t({
      ru: "Телефон",
      en: "Phone",
      he: "טלפון",
      ar: "الهاتف",
      uk: "Телефон",
    }),
    facebookPlaceholder: t({
      ru: "Ссылка на Facebook (опционально)",
      en: "Facebook link (optional)",
      he: "קישור לפייסבוק (אופציונלי)",
      ar: "رابط فيسبوك (اختياري)",
      uk: "Посилання на Facebook (опціонально)",
    }),
    genderLabel: t({
      ru: "Пол:",
      en: "Gender:",
      he: "מין:",
      ar: "الجنس:",
      uk: "Стать:",
    }),
    languagesLabel: t({
      ru: "Языки:",
      en: "Languages:",
      he: "שפות:",
      ar: "اللغات:",
      uk: "Мови:",
    }),
    nativeLanguageLabel: t({
      ru: "Родной язык:",
      en: "Native language:",
      he: "שפת אם:",
      ar: "اللغة الأم:",
      uk: "Рідна мова:",
    }),
    announcementPlaceholder: t({
      ru: "Объявление (детально)",
      en: "Announcement (detailed)",
      he: "הכרזה (מפורטת)",
      ar: "إعلان (مفصل)",
      uk: "Оголошення (детально)",
    }),
    notePlaceholder: t({
      ru: "Примечание",
      en: "Note",
      he: "הערה",
      ar: "ملاحظة",
      uk: "Примітка",
    }),
  },
} satisfies Dictionary;

export default addSeekerModalContent;