import { t, type Dictionary } from "intlayer";

const jobFormFieldsContent = {
  key: "jobFormFields",
  content: {
    jobTitle: t({
      ru: "Название вакансии",
      en: "Job title",
      he: "כותרת המשרה",
      ar: "عنوان الوظيفة",
      uk: "Назва вакансії",
    }),
    writeJobTitle: t({
      ru: "Введите название вакансии",
      en: "Enter job title",
      he: "הזן כותרת משרה",
      ar: "أدخل عنوان الوظيفة",
      uk: "Введіть назву вакансії",
    }),
    salaryPerHour: t({
      ru: "Зарплата в час",
      en: "Salary per hour",
      he: "שכר לשעה",
      ar: "الراتب في الساعة",
      uk: "Зарплата на годину",
    }),
    writeSalary: t({
      ru: "Введите зарплату",
      en: "Enter salary",
      he: "הזן שכר",
      ar: "أدخل الراتب",
      uk: "Введіть зарплату",
    }),
    location: t({
      ru: "Местоположение",
      en: "Location",
      he: "מיקום",
      ar: "الموقع",
      uk: "Місцезнаходження",
    }),
    locationPlaceholder: t({
      ru: "Выберите город",
      en: "Choose city",
      he: "בחר עיר",
      ar: "اختر المدينة",
      uk: "Оберіть місто",
    }),
    category: t({
      ru: "Категория",
      en: "Category",
      he: "קטגוריה",
      ar: "الفئة",
      uk: "Категорія",
    }),
    categoryPlaceholder: t({
      ru: "Выберите категорию",
      en: "Choose category",
      he: "בחר קטגוריה",
      ar: "اختر الفئة",
      uk: "Оберіть категорію",
    }),
    phoneNumber: t({
      ru: "Номер телефона",
      en: "Phone number",
      he: "מספר טלפון",
      ar: "رقم الهاتف",
      uk: "Номер телефону",
    }),
    writePhoneNumber: t({
      ru: "Введите номер телефона",
      en: "Enter phone number",
      he: "הזן מספר טלפון",
      ar: "أدخل رقم الهاتف",
      uk: "Введіть номер телефону",
    }),
    description: t({
      ru: "Описание",
      en: "Description",
      he: "תיאור",
      ar: "الوصف",
      uk: "Опис",
    }),
    writeJobDescription: t({
      ru: "Введите описание вакансии",
      en: "Enter job description",
      he: "הזן תיאור משרה",
      ar: "أدخل وصف الوظيفة",
      uk: "Введіть опис вакансії",
    }),
    shuttle: t({
      ru: "Подвозка",
      en: "Shuttle",
      he: "הסעה",
      ar: "النقل",
      uk: "Підвезення",
    }),
    meals: t({
      ru: "Питание",
      en: "Meals",
      he: "ארוחות",
      ar: "الوجبات",
      uk: "Харчування",
    }),
    termsAgreement: t({
      ru: "Я согласен с",
      en: "I agree with",
      he: "אני מסכים עם",
      ar: "أوافق على",
      uk: "Я згоден з",
    }),
    termsAgreementLink: t({
      ru: "пользовательским соглашением",
      en: "terms of service",
      he: "תנאי השירות",
      ar: "شروط الخدمة",
      uk: "угодою користувача",
    }),
    publishing: t({
      ru: "Публикуем",
      en: "Publishing",
      he: "מפרסם",
      ar: "نشر",
      uk: "Публікуємо",
    }),
    create: t({
      ru: "Опубликовать",
      en: "Publish",
      he: "פרסם",
      ar: "نشر",
      uk: "Опублікувати",
    }),
  },
} satisfies Dictionary;

export default jobFormFieldsContent;
