import { t, type Dictionary } from "intlayer";

const newsletterSubscriptionContent = {
  key: "newsletterSubscription",
  content: {
    newsletterTitle: t({
      ru: "Подписка на рассылку",
      en: "Newsletter Subscription",
      he: "מנוי לניוזלטר",
      ar: "اشتراك النشرة الإخبارية",
      uk: "Підписка на розсилку",
    }),
    newsletterDescription: t({
      ru: "Подпишитесь на нашу рассылку, чтобы получать уведомления о новых соискателях и обновлениях платформы.",
      en: "Subscribe to our newsletter to receive notifications about new job seekers and platform updates.",
      he: "הירשמו לניוזלטר שלנו כדי לקבל התראות על מחפשי עבודה חדשים ועדכוני הפלטפורמה.",
      ar: "اشترك في نشرتنا الإخبارية لتلقي إشعارات حول الباحثين عن عمل الجدد وتحديثات المنصة.",
      uk: "Підпишіться на нашу розсилку, щоб отримувати сповіщення про нових шукачів роботи та оновлення платформи.",
    }),
    newsletterBasicInfo: t({
      ru: "Основная информация",
      en: "Basic Information",
      he: "מידע בסיסי",
      ar: "المعلومات الأساسية",
      uk: "Основна інформація",
    }),
    newsletterFirst_name: t({
      ru: "Имя (необязательно)",
      en: "First Name (optional)",
      he: "שם פרטי (אופציונלי)",
      ar: "الاسم الأول (اختياري)",
      uk: "Ім'я (необов'язково)",
    }),
    newsletterFirst_namePlaceholder: t({
      ru: "Введите ваше имя",
      en: "Enter your first name",
      he: "הזן את השם הפרטי שלך",
      ar: "أدخل اسمك الأول",
      uk: "Введіть ваше ім'я",
    }),
    newsletterLast_name: t({
      ru: "Фамилия (необязательно)",
      en: "Last Name (optional)",
      he: "שם משפחה (אופציונלי)",
      ar: "اسم العائلة (اختياري)",
      uk: "Прізвище (необов'язково)",
    }),
    newsletterLast_namePlaceholder: t({
      ru: "Введите вашу фамилию",
      en: "Enter your last name",
      he: "הזן את שם המשפחה שלך",
      ar: "أدخل اسم عائلتك",
      uk: "Введіть ваше прізвище",
    }),
    newsletterEmailLabel: t({
      ru: "Email адрес *",
      en: "Email Address *",
      he: "כתובת אימייל *",
      ar: "عنوان البريد الإلكتروني *",
      uk: "Email адреса *",
    }),
    newsletterEmailPlaceholder: t({
      ru: "Введите ваш email",
      en: "Enter your email",
      he: "הזן את האימייל שלך",
      ar: "أدخل بريدك الإلكتروني",
      uk: "Введіть ваш email",
    }),
    newsletterNotificationSettings: t({
      ru: "Настройки уведомлений",
      en: "Notification Settings",
      he: "הגדרות התראות",
      ar: "إعدادات الإشعارات",
      uk: "Налаштування сповіщень",
    }),
    premiumFeatures: t({
      ru: "Премиум функции",
      en: "Premium Features",
      he: "תכונות פרימיום",
      ar: "الميزات المميزة",
      uk: "Преміум функції",
    }),
    newsletterPremiumUpgradeMessage: t({
      ru: "Обновитесь до премиум для доступа к расширенным фильтрам.",
      en: "Upgrade to premium for access to advanced filters.",
      he: "שדרג לפרימיום לגישה לפילטרים מתקדמים.",
      ar: "قم بالترقية إلى المميز للوصول إلى المرشحات المتقدمة.",
      uk: "Оновіться до преміум для доступу до розширених фільтрів.",
    }),
    newsletterGoToPlans: t({
      ru: "Перейти к планам",
      en: "Go to Plans",
      he: "עבור לתוכניות",
      ar: "انتقل إلى الخطط",
      uk: "Перейти до планів",
    }),
    city: t({
      ru: "Города",
      en: "Cities",
      he: "ערים",
      ar: "المدن",
      uk: "Міста",
    }),
    newsletterCategories: t({
      ru: "Категории",
      en: "Categories",
      he: "קטגוריות",
      ar: "الفئات",
      uk: "Категорії",
    }),
    newsletterEmploymentType: t({
      ru: "Тип занятости",
      en: "Employment Type",
      he: "סוג תעסוקה",
      ar: "نوع التوظيف",
      uk: "Тип зайнятості",
    }),
    languages: t({
      ru: "Языки",
      en: "Languages",
      he: "שפות",
      ar: "اللغات",
      uk: "Мови",
    }),
    newsletterLanguagesPremiumMessage: t({
      ru: "Фильтр по языкам доступен в премиум версии.",
      en: "Language filter is available in premium version.",
      he: "פילטר שפות זמין בגרסת פרימיום.",
      ar: "مرشح اللغة متاح في النسخة المميزة.",
      uk: "Фільтр за мовами доступний у преміум версії.",
    }),
    gender: t({
      ru: "Пол",
      en: "Gender",
      he: "מין",
      ar: "الجنس",
      uk: "Стать",
    }),
    newsletterGenderPremiumMessage: t({
      ru: "Фильтр по полу доступен в премиум версии.",
      en: "Gender filter is available in premium version.",
      he: "פילטר מין זמין בגרסת פרימיום.",
      ar: "مرشح الجنس متاح في النسخة المميزة.",
      uk: "Фільтр за статтю доступний у преміум версії.",
    }),
    documentType: t({
      ru: "Тип документа",
      en: "Document Type",
      he: "סוג מסמך",
      ar: "نوع المستند",
      uk: "Тип документа",
    }),
    newsletterDocumentTypePremiumMessage: t({
      ru: "Фильтр по типу документа доступен в премиум версии.",
      en: "Document type filter is available in premium version.",
      he: "פילטר סוג מסמך זמין בגרסת פרימיום.",
      ar: "مرشح نوع المستند متاح في النسخة المميزة.",
      uk: "Фільтр за типом документа доступний у преміум версії.",
    }),
    newsletterDemandedPremiumMessage: t({
      ru: "Фильтр по востребованным кандидатам доступен в премиум версии.",
      en: "Demanded candidates filter is available in premium version.",
      he: "פילטר מועמדים מבוקשים זמין בגרסת פרימיום.",
      ar: "مرشح المرشحين المطلوبين متاح في النسخة المميزة.",
      uk: "Фільтр за затребуваними кандидатами доступний у преміум версії.",
    }),
    newsletterDemandedCandidates: t({
      ru: "Только востребованные кандидаты",
      en: "Only Demanded Candidates",
      he: "רק מועמדים מבוקשים",
      ar: "المرشحون المطلوبون فقط",
      uk: "Тільки затребувані кандидати",
    }),
    newsletterAlreadySubscribed: t({
      ru: "Вы уже подписаны на рассылку!",
      en: "You are already subscribed to the newsletter!",
      he: "אתה כבר רשום לניוזלטר!",
      ar: "أنت مشترك بالفعل في النشرة الإخبارية!",
      uk: "Ви вже підписані на розсилку!",
    }),
    newsletterUnsubscribing: t({
      ru: "Отписка...",
      en: "Unsubscribing...",
      he: "מבטל מנוי...",
      ar: "جاري إلغاء الاشتراك...",
      uk: "Відписка...",
    }),
    newsletterUnsubscribe: t({
      ru: "Отписаться",
      en: "Unsubscribe",
      he: "בטל מנוי",
      ar: "إلغاء الاشتراك",
      uk: "Відписатися",
    }),
    newsletterSubscribing: t({
      ru: "Подписка...",
      en: "Subscribing...",
      he: "מתחבר...",
      ar: "جاري الاشتراك...",
      uk: "Підписка...",
    }),
    newsletterSubscribe: t({
      ru: "Подписаться",
      en: "Subscribe",
      he: "הרשם",
      ar: "اشترك",
      uk: "Підписатися",
    }),
    newsletterEmailRequired: t({
      ru: "Пожалуйста, введите email",
      en: "Please enter email",
      he: "אנא הזן אימייל",
      ar: "يرجى إدخال البريد الإلكتروني",
      uk: "Будь ласка, введіть email",
    }),
    newsletterInvalidEmail: t({
      ru: "Пожалуйста, введите корректный email",
      en: "Please enter a valid email",
      he: "אנא הזן אימייל תקין",
      ar: "يرجى إدخال بريد إلكتروني صحيح",
      uk: "Будь ласка, введіть коректний email",
    }),
    verificationCodeSent: t({
      ru: "Код подтверждения отправлен на ваш email!",
      en: "Verification code sent to your email!",
      he: "קוד אימות נשלח לאימייל שלך!",
      ar: "تم إرسال رمز التحقق إلى بريدك الإلكتروني!",
      uk: "Код підтвердження надіслано на ваш email!",
    }),
    newsletterError: t({
      ru: "Ошибка при отправке кода подтверждения",
      en: "Error sending verification code",
      he: "שגיאה בשליחת קוד אימות",
      ar: "خطأ في إرسال رمز التحقق",
      uk: "Помилка при надсиланні коду підтвердження",
    }),
    newsletterUnsubscribeSuccess: t({
      ru: "Вы успешно отписались от рассылки!",
      en: "You have successfully unsubscribed from the newsletter!",
      he: "ביטלת בהצלחה את המנוי לניוזלטר!",
      ar: "لقد ألغيت الاشتراك في النشرة الإخبارية بنجاح!",
      uk: "Ви успішно відписалися від розсилки!",
    }),
    newsletterUnsubscribeError: t({
      ru: "Ошибка при отписке от рассылки",
      en: "Error unsubscribing from newsletter",
      he: "שגיאה בביטול המנוי לניוזלטר",
      ar: "خطأ في إلغاء الاشتراك في النشرة الإخبارية",
      uk: "Помилка при відписці від розсилки",
    }),
    // Language options
    languageRussian: t({
      ru: "Русский",
      en: "Russian",
      he: "רוסית",
      ar: "الروسية",
      uk: "Російська",
    }),
    languageUkrainian: t({
      ru: "Украинский",
      en: "Ukrainian",
      he: "אוקראינית",
      ar: "الأوكرانية",
      uk: "Українська",
    }),
    languageEnglish: t({
      ru: "Английский",
      en: "English",
      he: "אנגלית",
      ar: "الإنجليزية",
      uk: "Англійська",
    }),
    languageHebrew: t({
      ru: "Иврит",
      en: "Hebrew",
      he: "עברית",
      ar: "العبرية",
      uk: "Іврит",
    }),
    // Employment options
    employmentFull: t({
      ru: "Полная",
      en: "Full-time",
      he: "מלאה",
      ar: "دوام كامل",
      uk: "Повна",
    }),
    employmentPartial: t({
      ru: "Частичная",
      en: "Part-time",
      he: "חלקית",
      ar: "دوام جزئي",
      uk: "Часткова",
    }),
    // Document type options
    documentVisaB1: t({
      ru: "Виза Б1",
      en: "Visa B1",
      he: "ויזה B1",
      ar: "تأشيرة B1",
      uk: "Віза Б1",
    }),
    documentVisaB2: t({
      ru: "Виза Б2",
      en: "Visa B2",
      he: "ויזה B2",
      ar: "تأشيرة B2",
      uk: "Віза Б2",
    }),
    documentTeudatZehut: t({
      ru: "Теудат Зеут",
      en: "Teudat Zehut",
      he: "תעודת זהות",
      ar: "هوية شخصية",
      uk: "Теудат Зеут",
    }),
    documentWorkVisa: t({
      ru: "Рабочая виза",
      en: "Work Visa",
      he: "ויזה לעבודה",
      ar: "تأشيرة عمل",
      uk: "Робоча віза",
    }),
    documentOther: t({
      ru: "Другое",
      en: "Other",
      he: "אחר",
      ar: "أخرى",
      uk: "Інше",
    }),
    // Gender options
    genderMale: t({
      ru: "Мужчина",
      en: "Male",
      he: "גבר",
      ar: "ذكر",
      uk: "Чоловік",
    }),
    genderFemale: t({
      ru: "Женщина",
      en: "Female",
      he: "אישה",
      ar: "أنثى",
      uk: "Жінка",
    }),
  },
} satisfies Dictionary;

export default newsletterSubscriptionContent;