import { t, type Dictionary } from "intlayer";

const newsletterModalContent = {
  key: "newsletterModal",
  content: {
    // Basic fields
    category: t({
      ru: "Категория",
      en: "Category",
      he: "קטגוריה",
      ar: "الفئة",
      uk: "Категорія",
    }),
    city: t({
      ru: "Город",
      en: "City",
      he: "עיר",
      ar: "المدينة",
      uk: "Місто",
    }),
    demanded: t({
      ru: "Востребованный",
      en: "In demand",
      he: "מבוקש",
      ar: "مطلوب",
      uk: "Затребуваний",
    }),
    employment: t({
      ru: "Занятость",
      en: "Employment",
      he: "תעסוקה",
      ar: "العمالة",
      uk: "Зайнятість",
    }),
    gender: t({
      ru: "Пол",
      en: "Gender",
      he: "מין",
      ar: "الجنس",
      uk: "Стать",
    }),
    languages: t({
      ru: "Языки",
      en: "Languages",
      he: "שפות",
      ar: "اللغات",
      uk: "Мови",
    }),
    
    // Document types
    documentType: t({
      ru: "Тип документа",
      en: "Document type",
      he: "סוג מסמך",
      ar: "نوع الوثيقة",
      uk: "Тип документа",
    }),
    documentOther: t({
      ru: "Другое",
      en: "Other",
      he: "אחר",
      ar: "أخرى",
      uk: "Інше",
    }),
    documentTeudatZehut: t({
      ru: "Теудат зеут",
      en: "Teudat zehut",
      he: "תעודת זהות",
      ar: "هوية شخصية",
      uk: "Теудат зеут",
    }),
    documentVisaB1: t({
      ru: "Виза Б1",
      en: "Visa B1",
      he: "ויזה B1",
      ar: "فيزا B1",
      uk: "Віза Б1",
    }),
    documentVisaB2: t({
      ru: "Виза Б2",
      en: "Visa B2",
      he: "ויזה B2",
      ar: "فيزا B2",
      uk: "Віза Б2",
    }),
    documentWorkVisa: t({
      ru: "Рабочая виза",
      en: "Work visa",
      he: "ויזת עבודה",
      ar: "فيزا عمل",
      uk: "Робоча віза",
    }),
    
    // Employment types
    employmentFull: t({
      ru: "Полная",
      en: "Full-time",
      he: "מלא",
      ar: "دوام كامل",
      uk: "Повна",
    }),
    employmentPartial: t({
      ru: "Частичная",
      en: "Part-time",
      he: "חלקי",
      ar: "دوام جزئي",
      uk: "Часткова",
    }),
    
    // Gender types
    genderFemale: t({
      ru: "Женщина",
      en: "Female",
      he: "אישה",
      ar: "أنثى",
      uk: "Жінка",
    }),
    genderMale: t({
      ru: "Мужчина",
      en: "Male",
      he: "גבר",
      ar: "ذكر",
      uk: "Чоловік",
    }),
    
    // Languages
    languageEnglish: t({
      ru: "Английский",
      en: "English",
      he: "אנגלית",
      ar: "الإنجليزية",
      uk: "Англійська",
    }),
    languageHebrew: t({
      ru: "Иврит",
      en: "Hebrew",
      he: "עברית",
      ar: "العبرية",
      uk: "Іврит",
    }),
    languageRussian: t({
      ru: "Русский",
      en: "Russian",
      he: "רוסית",
      ar: "الروسية",
      uk: "Російська",
    }),
    languageUkrainian: t({
      ru: "Украинский",
      en: "Ukrainian",
      he: "אוקראינית",
      ar: "الأوكرانية",
      uk: "Українська",
    }),
    
    // Newsletter specific
    newsletterTitle: t({
      ru: "Подписка на рассылку",
      en: "Newsletter subscription",
      he: "מנוי לניוזלטר",
      ar: "اشتراك النشرة الإخبارية",
      uk: "Підписка на розсилку",
    }),
    newsletterDescription: t({
      ru: "Получайте уведомления о новых вакансиях по вашим критериям",
      en: "Get notifications about new jobs matching your criteria",
      he: "קבל התראות על משרות חדשות המתאימות לקריטריונים שלך",
      ar: "احصل على إشعارات حول الوظائف الجديدة التي تطابق معاييرك",
      uk: "Отримуйте сповіщення про нові вакансії за вашими критеріями",
    }),
    newsletterEmailLabel: t({
      ru: "Email",
      en: "Email",
      he: "אימייל",
      ar: "البريد الإلكتروني",
      uk: "Email",
    }),
    newsletterEmailPlaceholder: t({
      ru: "Введите ваш email",
      en: "Enter your email",
      he: "הזן את האימייל שלך",
      ar: "أدخل بريدك الإلكتروني",
      uk: "Введіть ваш email",
    }),
    newsletterEmailRequired: t({
      ru: "Email обязателен",
      en: "Email is required",
      he: "אימייל נדרש",
      ar: "البريد الإلكتروني مطلوب",
      uk: "Email обов'язковий",
    }),
    newsletterInvalidEmail: t({
      ru: "Неверный формат email",
      en: "Invalid email format",
      he: "פורמט אימייל לא תקין",
      ar: "تنسيق البريد الإلكتروني غير صحيح",
      uk: "Невірний формат email",
    }),
    newsletterFirstName: t({
      ru: "Имя",
      en: "First name",
      he: "שם פרטי",
      ar: "الاسم الأول",
      uk: "Ім'я",
    }),
    newsletterFirstNamePlaceholder: t({
      ru: "Введите ваше имя",
      en: "Enter your first name",
      he: "הזן את השם הפרטי שלך",
      ar: "أدخل اسمك الأول",
      uk: "Введіть ваше ім'я",
    }),
    newsletterLastName: t({
      ru: "Фамилия",
      en: "Last name",
      he: "שם משפחה",
      ar: "الاسم الأخير",
      uk: "Прізвище",
    }),
    newsletterLastNamePlaceholder: t({
      ru: "Введите вашу фамилию",
      en: "Enter your last name",
      he: "הזן את שם המשפחה שלך",
      ar: "أدخل اسمك الأخير",
      uk: "Введіть ваше прізвище",
    }),
    newsletterSubscribe: t({
      ru: "Подписаться",
      en: "Subscribe",
      he: "הירשם",
      ar: "اشترك",
      uk: "Підписатися",
    }),
    newsletterSubscribing: t({
      ru: "Подписываемся...",
      en: "Subscribing...",
      he: "נרשם...",
      ar: "جاري الاشتراك...",
      uk: "Підписуємося...",
    }),
    newsletterAlreadySubscribed: t({
      ru: "Вы уже подписаны на рассылку",
      en: "You are already subscribed to the newsletter",
      he: "אתה כבר רשום לניוזלטר",
      ar: "أنت مشترك بالفعل في النشرة الإخبارية",
      uk: "Ви вже підписані на розсилку",
    }),
    newsletterError: t({
      ru: "Ошибка подписки на рассылку",
      en: "Newsletter subscription error",
      he: "שגיאה בהרשמה לניוזלטר",
      ar: "خطأ في الاشتراك في النشرة الإخبارية",
      uk: "Помилка підписки на розсилку",
    }),
    newsletterUnsubscribeSuccess: t({
      ru: "Вы успешно отписались от рассылки",
      en: "You have successfully unsubscribed from the newsletter",
      he: "ביטלת בהצלחה את המנוי לניוזלטר",
      ar: "لقد ألغيت الاشتراك بنجاح من النشرة الإخبارية",
      uk: "Ви успішно відписалися від розсилки",
    }),
    newsletterUnsubscribeError: t({
      ru: "Ошибка отписки от рассылки",
      en: "Newsletter unsubscribe error",
      he: "שגיאה בביטול המנוי לניוזלטר",
      ar: "خطأ في إلغاء الاشتراك في النشرة الإخبارية",
      uk: "Помилка відписки від розсилки",
    }),
    newsletterUnsubscribing: t({
      ru: "Отписываемся...",
      en: "Unsubscribing...",
      he: "מבטל מנוי...",
      ar: "جاري إلغاء الاشتراك...",
      uk: "Відписуємося...",
    }),
    unsubscribe: t({
      ru: "Отписаться",
      en: "Unsubscribe",
      he: "בטל מנוי",
      ar: "إلغاء الاشتراك",
      uk: "Відписатися",
    }),
    verificationCodeSent: t({
      ru: "Код подтверждения отправлен",
      en: "Verification code sent",
      he: "קוד אימות נשלח",
      ar: "تم إرسال رمز التحقق",
      uk: "Код підтвердження надіслано",
    }),
  },
} satisfies Dictionary;

export default newsletterModalContent;