import { t, type Dictionary } from 'intlayer';

const premiumPageContent = {
	key: 'premiumPage',
	content: {
		pricingTitle: t({
			ru: 'ПРЕМИУМ ПОДПИСКА',
			en: 'PREMIUM SUBSCRIPTION',
			he: 'מנוי פרימיום',
			ar: 'اشتراك بريميوم',
			uk: 'ПРЕМІУМ ПІДПИСКА',
		}),
		pricingEffective: t({
			ru: 'ЭФФЕКТИВНО',
			en: 'EFFECTIVE',
			he: 'יעיל',
			ar: 'فعال',
			uk: 'ЕФЕКТИВНО',
		}),
		pricingConvenient: t({
			ru: 'УДОБНО',
			en: 'CONVENIENT',
			he: 'נוח',
			ar: 'مريح',
			uk: 'ЗРУЧНО',
		}),
		pricingTrust: t({
			ru: 'НАДЕЖНО',
			en: 'TRUSTED',
			he: 'אמין',
			ar: 'موثوق',
			uk: 'НАДІЙНО',
		}),
		pricingDescription: t({
			ru: 'Выберите подходящий для вас тариф и начните использовать платформу на максимум! После оплаты подписка активна сразу и будет действовать в течение 30 дней. Вы можете отменить подписку в любое время.',
			en: 'Choose the right plan for you and start using the platform to the maximum! After payment, the subscription is active immediately and will be valid for 30 days. You can cancel your subscription at any time.',
			he: 'בחר את התוכנית המתאימה לך והתחל להשתמש בפלטפורמה במלואה! לאחר התשלום, המנוי פעיל מיד ויהיה תקף למשך 30 יום. תוכל לבטל את המנוי בכל עת.',
			ar: 'اختر الخطة المناسبة لك وابدأ في استخدام المنصة بأقصى حد! بعد الدفع، الاشتراك نشط فوراً وسيكون صالحاً لمدة 30 يوماً. يمكنك إلغاء الاشتراك في أي وقت.',
			uk: 'Оберіть підходящий для вас тариф і почніть використовувати платформу на максимум! Після оплати підписка активна одразу і буде діяти протягом 30 днів. Ви можете скасувати підписку в будь-який час.',
		}),
		loading: t({
			ru: 'Загрузка...',
			en: 'Loading...',
			he: 'טוען...',
			ar: 'جاري التحميل...',
			uk: 'Завантаження...',
		}),
		pricingDeluxeUpgradeToDeluxe: t({
			ru: 'Улучшить до Deluxe',
			en: 'Upgrade to Deluxe',
			he: 'שדרג לדלוקס',
			ar: 'ترقية إلى ديلوكس',
			uk: 'Покращити до Deluxe',
		}),
		userNotFound: t({
			ru: 'Пользователь не найден. Попробуйте войти заново.',
			en: 'User not found. Try logging in again.',
			he: 'משתמש לא נמצא. נסה להתחבר שוב.',
			ar: 'المستخدم غير موجود. حاول تسجيل الدخول مرة أخرى.',
			uk: 'Користувача не знайдено. Спробуйте увійти знову.',
		}),
		paymentError: t({
			ru: 'Ошибка оплаты. Попробуйте позже.',
			en: 'Payment error. Try again later.',
			he: 'שגיאת תשלום. נסה שוב מאוחר יותר.',
			ar: 'خطأ في الدفع. حاول مرة أخرى لاحقاً.',
			uk: 'Помилка оплати. Спробуйте пізніше.',
		}),
		// Pricing plans
		pricingFreeTitle: t({
			ru: 'Бесплатно',
			en: 'Free',
			he: 'חינם',
			ar: 'مجاني',
			uk: 'Безкоштовно',
		}),
		pricingProTitle: t({
			ru: 'Pro',
			en: 'Pro',
			he: 'פרו',
			ar: 'برو',
			uk: 'Pro',
		}),
		pricingDeluxeTitle: t({
			ru: 'Deluxe',
			en: 'Deluxe',
			he: 'דלוקס',
			ar: 'ديلوكس',
			uk: 'Deluxe',
		}),
		pricingRecommended: t({
			ru: 'Рекомендуемый',
			en: 'Recommended',
			he: 'מומלץ',
			ar: 'موصى به',
			uk: 'Рекомендований',
		}),
		pricingBestResults: t({
			ru: 'Лучший результат',
			en: 'Best results',
			he: 'התוצאות הטובות ביותר',
			ar: 'أفضل النتائج',
			uk: 'Найкращий результат',
		}),
		// Free plan features
		pricingFreeUpTo5Ads: t({
			ru: 'До 5 объявлений',
			en: 'Up to 5 ads',
			he: 'עד 5 מודעות',
			ar: 'حتى 5 إعلانات',
			uk: 'До 5 оголошень',
		}),
		pricingFreeDailyBoost: t({
			ru: 'Поднятие объявлений раз в сутки',
			en: 'Daily ad boost',
			he: 'הגבהת מודעות פעם ביום',
			ar: 'تعزيز الإعلانات يومياً',
			uk: 'Підняття оголошень раз на добу',
		}),
		pricingFreeBasicSupport: t({
			ru: 'Базовая поддержка',
			en: 'Basic support',
			he: 'תמיכה בסיסית',
			ar: 'دعم أساسي',
			uk: 'Базова підтримка',
		}),
		pricingFreeUseFree: t({
			ru: 'Использовать бесплатно',
			en: 'Use for free',
			he: 'השתמש בחינם',
			ar: 'استخدم مجاناً',
			uk: 'Використовувати безкоштовно',
		}),
		// Pro plan features
		pricingProUpTo10Ads: t({
			ru: 'До 10 объявлений',
			en: 'Up to 10 ads',
			he: 'עד 10 מודעות',
			ar: 'حتى 10 إعلانات',
			uk: 'До 10 оголошень',
		}),
		pricingProUnlimitedSeekerData: t({
			ru: 'Открывать данные соискателей без ограничений',
			en: 'Unlimited access to seeker data',
			he: 'גישה בלתי מוגבלת לנתוני מחפשי עבודה',
			ar: 'وصول غير محدود لبيانات الباحثين عن عمل',
			uk: 'Відкривати дані шукачів роботи без обмежень',
		}),
		pricingProTopJobs: t({
			ru: 'Вакансии в топе',
			en: 'Top job placement',
			he: 'מיקום משרות בראש',
			ar: 'وضع الوظائف في المقدمة',
			uk: 'Вакансії в топі',
		}),
		pricingProColorHighlighting: t({
			ru: 'Выделение цветом',
			en: 'Color highlighting',
			he: 'הדגשה בצבע',
			ar: 'تمييز بالألوان',
			uk: 'Виділення кольором',
		}),
		pricingProAdvancedFilters: t({
			ru: 'Расширенные фильтры для рассылки',
			en: 'Advanced newsletter filters',
			he: 'מסננים מתקדמים לניוזלטר',
			ar: 'مرشحات متقدمة للنشرة الإخبارية',
			uk: 'Розширені фільтри для розсилки',
		}),
		pricingProPrioritySupport: t({
			ru: 'Приоритетная поддержка',
			en: 'Priority support',
			he: 'תמיכה בעדיפות',
			ar: 'دعم ذو أولوية',
			uk: 'Пріоритетна підтримка',
		}),
		pricingProBuyPremium: t({
			ru: 'Купить Premium',
			en: 'Buy Premium',
			he: 'קנה פרימיום',
			ar: 'اشتر بريميوم',
			uk: 'Купити Premium',
		}),
		// Deluxe plan features
		pricingDeluxeAllFromPro: t({
			ru: 'Все из Pro тарифа',
			en: 'Everything from Pro plan',
			he: 'הכל מתוכנית פרו',
			ar: 'كل شيء من خطة برو',
			uk: 'Все з Pro тарифу',
		}),
		pricingDeluxePersonalManager: t({
			ru: 'Персональный менеджер',
			en: 'Personal manager',
			he: 'מנהל אישי',
			ar: 'مدير شخصي',
			uk: 'Персональний менеджер',
		}),
		pricingDeluxeFacebookAutoposting: t({
			ru: 'Доступ к функциям автопостинга в группах Facebook',
			en: 'Access to Facebook group autoposting features',
			he: 'גישה לתכונות פרסום אוטומטי בקבוצות פייסבוק',
			ar: 'الوصول إلى ميزات النشر التلقائي في مجموعات فيسبوك',
			uk: 'Доступ до функцій автопостингу в групах Facebook',
		}),
		pricingDeluxeFacebookPromotion: t({
			ru: 'Активное продвижение ваших вакансий через Facebook',
			en: 'Active promotion of your jobs through Facebook',
			he: 'קידום פעיל של המשרות שלך דרך פייסבוק',
			ar: 'الترويج النشط لوظائفك عبر فيسبوك',
			uk: 'Активне просування ваших вакансій через Facebook',
		}),
		pricingDeluxePersonalMailing: t({
			ru: 'Персональная рассылка лучших кандидатов под ваши требования',
			en: 'Personal mailing of the best candidates according to your requirements',
			he: 'שליחה אישית של המועמדים הטובים ביותר לפי הדרישות שלך',
			ar: 'إرسال شخصي لأفضل المرشحين حسب متطلباتك',
			uk: 'Персональна розсилка найкращих кандидатів під ваші вимоги',
		}),
		pricingDeluxeTelegramPublications: t({
			ru: 'Публикации ваших вакансий в телеграм канале',
			en: 'Publication of your jobs in Telegram channel',
			he: 'פרסום המשרות שלך בערוץ טלגרם',
			ar: 'نشر وظائفك في قناة تلغرام',
			uk: 'Публікації ваших вакансій в телеграм каналі',
		}),
		pricingDeluxePersonalCandidateSelection: t({
			ru: 'Личный подбор кандидатов под ваши требования',
			en: 'Personal candidate selection according to your requirements',
			he: 'בחירה אישית של מועמדים לפי הדרישות שלך',
			ar: 'اختيار شخصي للمرشحين حسب متطلباتك',
			uk: 'Особистий підбір кандидатів під ваші вимоги',
		}),
		pricingDeluxeInterviewOrganization: t({
			ru: 'Организация собеседований',
			en: 'Interview organization',
			he: 'ארגון ראיונות',
			ar: 'تنظيم المقابلات',
			uk: 'Організація співбесід',
		}),
		pricingDeluxeBuyDeluxe: t({
			ru: 'Купить Deluxe',
			en: 'Buy Deluxe',
			he: 'קנה דלוקס',
			ar: 'اشتر ديلوكس',
			uk: 'Купити Deluxe',
		}),
		active: t({
			ru: 'Активно',
			en: 'Active',
			he: 'פעיל',
			ar: 'نشط',
			uk: 'Активно',
		}),
	},
} satisfies Dictionary;

export default premiumPageContent;
