import { type Dictionary, t } from 'intlayer';

const seekersContent = {
	key: 'seekers',
	content: {
		seekersHelmet: t({
			ru: 'Соискатели - WorkNow',
			en: 'Job Seekers - WorkNow',
			he: 'מחפשי עבודה - WorkNow',
			ar: 'الباحثون عن عمل - WorkNow',
			uk: 'Шукачі роботи - WorkNow',
		}),
		seekersDescription: t({
			ru: 'Список соискателей на вакансии',
			en: 'List of job seekers',
			he: 'רשימת מחפשי עבודה',
			ar: 'قائمة الباحثين عن عمل',
			uk: 'Список шукачів роботи',
		}),
		seekersDatabaseUpdate: t({
			ru: 'База данных кандидатов обновляется ежедневно',
			en: 'Candidate database is updated daily',
			he: 'מסד הנתונים של המועמדים מתעדכן מדי יום',
			ar: 'قاعدة بيانات المرشحين محدثة يومياً',
			uk: 'База даних кандидатів оновлюється щодня',
		}),
		seekersDatabaseUpdateDescription: t({
			ru: 'Новые кандидаты добавляются каждый день',
			en: 'New candidates are added every day',
			he: 'מועמדים חדשים מתווספים מדי יום',
			ar: 'يتم إضافة مرشحين جدد كل يوم',
			uk: 'Нові кандидати додаються кожен день',
		}),
		seekersAddYourself: t({
			ru: 'Если хотите добавить себя в этот список, напишите в WhatsApp - 053-3033332',
			en: 'If you want to add yourself to this list, write to WhatsApp - 053-3033332',
			he: 'אם אתה רוצה להוסיף את עצמך לרשימה זו, כתוב לווטסאפ - 053-3033332',
			ar: 'إذا كنت تريد إضافة نفسك إلى هذه القائمة، اكتب إلى واتساب - 053-3033332',
			uk: 'Якщо хочете додати себе до цього списку, напишіть у WhatsApp - 053-3033332',
		}),
		facebookProfile: t({
			ru: 'Профиль в Facebook',
			en: 'Facebook profile',
			he: 'פרופיל בפייסבוק',
			ar: 'الملف الشخصي على فيسبوك',
			uk: 'Профіль у Facebook',
		}),
		addSeeker: t({
			ru: 'Добавить соискателя',
			en: 'Add job seeker',
			he: 'הוסף מחפש עבודה',
			ar: 'أضف باحث عن عمل',
			uk: 'Додати шукача роботи',
		}),
		noSeekersFound: t({
			ru: 'Соискатели не найдены',
			en: 'No job seekers found',
			he: 'לא נמצאו מחפשי עבודה',
			ar: 'لم يتم العثور على باحثين عن عمل',
			uk: 'Шукачі роботи не знайдені',
		}),
		noSeekersDescription: t({
			ru: 'Попробуйте изменить фильтры поиска',
			en: 'Try changing search filters',
			he: 'נסה לשנות את מסנני החיפוש',
			ar: 'حاول تغيير مرشحات البحث',
			uk: 'Спробуйте змінити фільтри пошуку',
		}),
		seekersTableName: t({
			ru: 'Имя',
			en: 'Name',
			he: 'שם',
			ar: 'الاسم',
			uk: "Ім'я",
		}),
		seekersTableContact: t({
			ru: 'Контакты',
			en: 'Contact',
			he: 'יצירת קשר',
			ar: 'التواصل',
			uk: 'Контакти',
		}),
		seekersTableCity: t({
			ru: 'Город',
			en: 'City',
			he: 'עיר',
			ar: 'المدينة',
			uk: 'Місто',
		}),
		seekersTableDescription: t({
			ru: 'Описание',
			en: 'Description',
			he: 'תיאור',
			ar: 'الوصف',
			uk: 'Опис',
		}),
		loading: t({
			ru: 'Загрузка...',
			en: 'Loading...',
			he: 'טוען...',
			ar: 'جاري التحميل...',
			uk: 'Завантаження...',
		}),
		errorAddingSeeker: t({
			ru: 'Ошибка при добавлении соискателя',
			en: 'Error adding job seeker',
			he: 'שגיאה בהוספת מחפש עבודה',
			ar: 'خطأ في إضافة باحث عن عمل',
			uk: 'Помилка при додаванні шукача роботи',
		}),
		seekers: t({
			ru: 'Соискатели',
			en: 'Job Seekers',
			he: 'מחפשי עבודה',
			ar: 'الباحثون عن عمل',
			uk: 'Шукачі роботи',
		}),
		filters: t({
			ru: 'Фильтры',
			en: 'Filters',
			he: 'מסננים',
			ar: 'المرشحات',
			uk: 'Фільтри',
		}),
		newsletter: t({
			ru: 'Рассылка',
			en: 'Newsletter',
			he: 'ניוזלטר',
			ar: 'النشرة الإخبارية',
			uk: 'Розсилка',
		}),
		deleteSeeker: t({
			ru: 'Удалить соискателя',
			en: 'Delete job seeker',
			he: 'מחק מחפש עבודה',
			ar: 'حذف باحث عن عمل',
			uk: 'Видалити шукача роботи',
		}),
		confirmDelete: t({
			ru: 'Подтвердить удаление',
			en: 'Confirm deletion',
			he: 'אשר מחיקה',
			ar: 'تأكيد الحذف',
			uk: 'Підтвердити видалення',
		}),
		cancel: t({
			ru: 'Отмена',
			en: 'Cancel',
			he: 'ביטול',
			ar: 'إلغاء',
			uk: 'Скасувати',
		}),
		deleteConfirmation: t({
			ru: 'Удалить выбранных соискателей?',
			en: 'Delete selected job seekers?',
			he: 'למחוק מחפשי עבודה שנבחרו?',
			ar: 'حذف الباحثين عن عمل المحددين؟',
			uk: 'Видалити обраних шукачів роботи?',
		}),
		successfullyDeleted: t({
			ru: 'Успешно удалено',
			en: 'Successfully deleted',
			he: 'נמחק בהצלחה',
			ar: 'تم الحذف بنجاح',
			uk: 'Успішно видалено',
		}),
		errorDeleting: t({
			ru: 'Ошибка при удалении',
			en: 'Error deleting',
			he: 'שגיאה במחיקה',
			ar: 'خطأ في الحذف',
			uk: 'Помилка при видаленні',
		}),
		filtersApplied: t({
			ru: 'Фильтры применены',
			en: 'Filters applied',
			he: 'מסננים יושמו',
			ar: 'تم تطبيق المرشحات',
			uk: 'Фільтри застосовано',
		}),
		noSeekersOnPage: t({
			ru: 'Нет соискателей на текущей странице',
			en: 'No job seekers on current page',
			he: 'אין מחפשי עבודה בעמוד הנוכחי',
			ar: 'لا يوجد باحثون عن عمل في الصفحة الحالية',
			uk: 'Немає шукачів роботи на поточній сторінці',
		}),
		noSeekersMatchingFilters: t({
			ru: 'Нет соискателей, соответствующих фильтрам на текущей странице',
			en: 'No job seekers matching filters on current page',
			he: 'אין מחפשי עבודה התואמים למסננים בעמוד הנוכחי',
			ar: 'لا يوجد باحثون عن عمل يطابقون المرشحات في الصفحة الحالية',
			uk: 'Немає шукачів роботи, що відповідають фільтрам на поточній сторінці',
		}),
		totalSeekers: t({
			ru: 'Всего соискателей:',
			en: 'Total job seekers:',
			he: 'סה"כ מחפשי עבודה:',
			ar: 'إجمالي الباحثين عن عمل:',
			uk: 'Всього шукачів роботи:',
		}),
		tryChangingFilters: t({
			ru: 'Попробуйте изменить фильтры или перейти на другую страницу.',
			en: 'Try changing filters or go to another page.',
			he: 'נסה לשנות מסננים או לעבור לעמוד אחר.',
			ar: 'حاول تغيير المرشحات أو الانتقال إلى صفحة أخرى.',
			uk: 'Спробуйте змінити фільтри або перейти на іншу сторінку.',
		}),
		goToAnotherPage: t({
			ru: 'Перейдите на другую страницу.',
			en: 'Go to another page.',
			he: 'עבור לעמוד אחר.',
			ar: 'انتقل إلى صفحة أخرى.',
			uk: 'Перейдіть на іншу сторінку.',
		}),
		returnToFirstPage: t({
			ru: 'Вернуться на первую страницу',
			en: 'Return to first page',
			he: 'חזור לעמוד הראשון',
			ar: 'العودة إلى الصفحة الأولى',
			uk: 'Повернутися на першу сторінку',
		}),
		showingSeekers: t({
			ru: 'Показано',
			en: 'Showing',
			he: 'מציג',
			ar: 'عرض',
			uk: 'Показано',
		}),
		ofSeekers: t({
			ru: 'из',
			en: 'of',
			he: 'מתוך',
			ar: 'من',
			uk: 'з',
		}),
		seekersCount: t({
			ru: 'соискателей',
			en: 'job seekers',
			he: 'מחפשי עבודה',
			ar: 'باحثين عن عمل',
			uk: 'шукачів роботи',
		}),
		filtersAppliedBadge: t({
			ru: 'Фильтры применены',
			en: 'Filters applied',
			he: 'מסננים יושמו',
			ar: 'تم تطبيق المرشحات',
			uk: 'Фільтри застосовано',
		}),
		usePaginationForNavigation: t({
			ru: 'Используйте пагинацию для навигации',
			en: 'Use pagination for navigation',
			he: 'השתמש בדפדוף לניווט',
			ar: 'استخدم الترقيم للتنقل',
			uk: 'Використовуйте пагінацію для навігації',
		}),
		manyPagesWarning: t({
			ru: 'Много страниц - используйте фильтры для ускорения поиска',
			en: 'Many pages - use filters to speed up search',
			he: 'הרבה עמודים - השתמש במסננים להאצת החיפוש',
			ar: 'صفحات كثيرة - استخدم المرشحات لتسريع البحث',
			uk: 'Багато сторінок - використовуйте фільтри для прискорення пошуку',
		}),
	},
} satisfies Dictionary;

export default seekersContent;
