import { t, type Dictionary } from "intlayer";

const seekerDetailsContent = {
  key: "seekerDetails",
  content: {
    seekerProfileLoading: t({
      ru: "Загрузка...",
      en: "Loading...",
      he: "טוען...",
      ar: "جاري التحميل...",
      uk: "Завантаження...",
    }),
    seekerProfileTitle: t({
      ru: "Профиль соискателя",
      en: "Job seeker profile",
      he: "פרופיל מחפש עבודה",
      ar: "ملف الباحث عن عمل",
      uk: "Профіль шукача роботи",
    }),
    seekerProfileNotFound: t({
      ru: "Профиль не найден",
      en: "Profile not found",
      he: "הפרופיל לא נמצא",
      ar: "الملف غير موجود",
      uk: "Профіль не знайдено",
    }),
    seekerProfileBack: t({
      ru: "Назад к списку",
      en: "Back to list",
      he: "חזרה לרשימה",
      ar: "العودة إلى القائمة",
      uk: "Назад до списку",
    }),
    seekerProfilePublished: t({
      ru: "Опубликовано {{days}} дней назад ({{date}})",
      en: "Published {{days}} days ago ({{date}})",
      he: "פורסם לפני {{days}} ימים ({{date}})",
      ar: "نُشر قبل {{days}} أيام ({{date}})",
      uk: "Опубліковано {{days}} днів тому ({{date}})",
    }),
    seekerProfileDemanded: t({
      ru: "Востребованный",
      en: "In demand",
      he: "נדרש",
      ar: "مطلوب",
      uk: "Затребуваний",
    }),
    seekerProfileContactsPremium: t({
      ru: "Контакты доступны в премиум версии",
      en: "Contacts available in premium version",
      he: "אנשי קשר זמינים בגרסת פרימיום",
      ar: "جهات الاتصال متاحة في النسخة المميزة",
      uk: "Контакти доступні у преміум версії",
    }),
    seekerProfileEmployment: t({
      ru: "Тип занятости",
      en: "Employment type",
      he: "סוג תעסוקה",
      ar: "نوع التوظيف",
      uk: "Тип зайнятості",
    }),
    seekerProfileCategory: t({
      ru: "Категория",
      en: "Category",
      he: "קטגוריה",
      ar: "الفئة",
      uk: "Категорія",
    }),
    seekerProfileLanguages: t({
      ru: "Языки",
      en: "Languages",
      he: "שפות",
      ar: "اللغات",
      uk: "Мови",
    }),
    seekerProfileNative: t({
      ru: "(родной)",
      en: "(native)",
      he: "(שפת אם)",
      ar: "(أصلي)",
      uk: "(рідна)",
    }),
    seekerProfileDocuments: t({
      ru: "Документы",
      en: "Documents",
      he: "מסמכים",
      ar: "المستندات",
      uk: "Документи",
    }),
    seekerProfileAnnouncement: t({
      ru: "Объявление",
      en: "Announcement",
      he: "הכרזה",
      ar: "الإعلان",
      uk: "Оголошення",
    }),
    seekerProfileNote: t({
      ru: "Примечание",
      en: "Note",
      he: "הערה",
      ar: "ملاحظة",
      uk: "Примітка",
    }),
    seekerProfileNotePremium: t({
      ru: "Примечание доступно в премиум версии",
      en: "Note available in premium version",
      he: "הערה זמינה בגרסת פרימיום",
      ar: "الملاحظة متاحة في النسخة المميزة",
      uk: "Примітка доступна у преміум версії",
    }),
    seekerProfilePrint: t({
      ru: "Печать",
      en: "Print",
      he: "הדפסה",
      ar: "طباعة",
      uk: "Друк",
    }),
    seekerProfileOf: t({
      ru: "{{current}} из {{total}}",
      en: "{{current}} of {{total}}",
      he: "{{current}} מתוך {{total}}",
      ar: "{{current}} من {{total}}",
      uk: "{{current}} з {{total}}",
    }),
    seekerProfilePrev: t({
      ru: "Предыдущий",
      en: "Previous",
      he: "הקודם",
      ar: "السابق",
      uk: "Попередній",
    }),
    seekerProfileNext: t({
      ru: "Следующий",
      en: "Next",
      he: "הבא",
      ar: "التالي",
      uk: "Наступний",
    }),
  },
} satisfies Dictionary;

export default seekerDetailsContent;