import { type Dictionary, t } from 'intlayer';

const userJobsContent = {
	key: 'userJobs',
	content: {
		signInToView: t({
			ru: 'Войдите, чтобы просмотреть ваши объявления',
			en: 'Sign in to view your advertisements',
			he: 'התחבר כדי לראות את המודעות שלך',
			ar: 'سجل الدخول لعرض إعلاناتك',
			uk: 'Увійдіть, щоб переглянути ваші оголошення',
		}),
		myAdsTitle: t({
			ru: 'Мои объявления',
			en: 'My advertisements',
			he: 'המודעות שלי',
			ar: 'إعلاناتي',
			uk: 'Мої оголошення',
		}),
		youDontHaveAds: t({
			ru: 'У вас пока нет объявлений',
			en: "You don't have any advertisements yet",
			he: 'אין לך מודעות עדיין',
			ar: 'ليس لديك إعلانات بعد',
			uk: 'У вас поки немає оголошень',
		}),
		premiumBadge: t({
			ru: 'Премиум',
			en: 'Premium',
			he: 'פרימיום',
			ar: 'بريميوم',
			uk: 'Преміум',
		}),
		notSpecified: t({
			ru: 'Не указано',
			en: 'Not specified',
			he: 'לא צוין',
			ar: 'غير محدد',
			uk: 'Не вказано',
		}),
		salaryPerHourCard: t({
			ru: 'Зарплата в час:',
			en: 'Salary per hour:',
			he: 'שכר לשעה:',
			ar: 'الراتب في الساعة:',
			uk: 'Зарплата на годину:',
		}),
		locationCard: t({
			ru: 'Местоположение:',
			en: 'Location:',
			he: 'מיקום:',
			ar: 'الموقع:',
			uk: 'Місцезнаходження:',
		}),
		shuttle: t({
			ru: 'Подвозка',
			en: 'Shuttle',
			he: 'הסעה',
			ar: 'النقل',
			uk: 'Підвезення',
		}),
		meals: t({
			ru: 'Питание',
			en: 'Meals',
			he: 'ארוחות',
			ar: 'الوجبات',
			uk: 'Харчування',
		}),
		yes: t({
			ru: 'Да',
			en: 'Yes',
			he: 'כן',
			ar: 'نعم',
			uk: 'Так',
		}),
		no: t({
			ru: 'Нет',
			en: 'No',
			he: 'לא',
			ar: 'لا',
			uk: 'Ні',
		}),
		phoneNumberCard: t({
			ru: 'Номер телефона:',
			en: 'Phone number:',
			he: 'מספר טלפון:',
			ar: 'رقم الهاتف:',
			uk: 'Номер телефону:',
		}),
		imageUnavailable: t({
			ru: 'Изображение\nнедоступно',
			en: 'Image\nunavailable',
			he: 'תמונה\nלא זמינה',
			ar: 'الصورة\nغير متاحة',
			uk: 'Зображення\nнедоступне',
		}),
		createdAt: t({
			ru: 'Создано',
			en: 'Created',
			he: 'נוצר',
			ar: 'تم الإنشاء',
			uk: 'Створено',
		}),
		nextBoostAfter: t({
			ru: 'Следующий буст через',
			en: 'Next boost in',
			he: 'הגבהה הבאה בעוד',
			ar: 'التعزيز التالي خلال',
			uk: 'Наступний буст через',
		}),
		hoursShort: t({
			ru: 'ч',
			en: 'h',
			he: "ש'",
			ar: 'س',
			uk: 'год',
		}),
		minutesShort: t({
			ru: 'м',
			en: 'm',
			he: "ד'",
			ar: 'د',
			uk: 'хв',
		}),
		boostReady: t({
			ru: 'Готов к бусту',
			en: 'Ready to boost',
			he: 'מוכן להגבהה',
			ar: 'جاهز للتعزيز',
			uk: 'Готовий до бусту',
		}),
		boostTitle: t({
			ru: 'Поднять объявление в топ',
			en: 'Boost advertisement to top',
			he: 'הגבה מודעה לראש',
			ar: 'تعزيز الإعلان للمقدمة',
			uk: 'Підняти оголошення в топ',
		}),
		confirmDelete: t({
			ru: 'Подтвердить удаление',
			en: 'Confirm deletion',
			he: 'אשר מחיקה',
			ar: 'تأكيد الحذف',
			uk: 'Підтвердити видалення',
		}),
		confirmDeleteText: t({
			ru: 'Вы уверены, что хотите удалить это объявление?',
			en: 'Are you sure you want to delete this advertisement?',
			he: 'האם אתה בטוח שברצונך למחוק את המודעה הזו?',
			ar: 'هل أنت متأكد من أنك تريد حذف هذا الإعلان؟',
			uk: 'Ви впевнені, що хочете видалити це оголошення?',
		}),
		cancel: t({
			ru: 'Отмена',
			en: 'Cancel',
			he: 'ביטול',
			ar: 'إلغاء',
			uk: 'Скасувати',
		}),
		delete: t({
			ru: 'Удалить',
			en: 'Delete',
			he: 'מחק',
			ar: 'حذف',
			uk: 'Видалити',
		}),
		// Success/Error messages
		jobDeletedSuccess: t({
			ru: 'Объявление удалено!',
			en: 'Advertisement deleted!',
			he: 'המודעה נמחקה!',
			ar: 'تم حذف الإعلان!',
			uk: 'Оголошення видалено!',
		}),
		jobDeletedError: t({
			ru: 'Ошибка удаления объявления!',
			en: 'Error deleting advertisement!',
			he: 'שגיאה במחיקת המודעה!',
			ar: 'خطأ في حذف الإعلان!',
			uk: 'Помилка видалення оголошення!',
		}),
		jobBoostedSuccess: t({
			ru: 'Объявление поднято в топ!',
			en: 'Advertisement boosted to top!',
			he: 'המודעה הוגבהה לראש!',
			ar: 'تم تعزيز الإعلان للمقدمة!',
			uk: 'Оголошення піднято в топ!',
		}),
		jobBoostedError: t({
			ru: 'Ошибка поднятия объявления',
			en: 'Error boosting advertisement',
			he: 'שגיאה בהגבהת המודעה',
			ar: 'خطأ في تعزيز الإعلان',
			uk: 'Помилка підняття оголошення',
		}),
		loadJobsError: t({
			ru: 'Ошибка загрузки ваших объявлений!',
			en: 'Error loading your advertisements!',
			he: 'שגיאה בטעינת המודעות שלך!',
			ar: 'خطأ في تحميل إعلاناتك!',
			uk: 'Помилка завантаження ваших оголошень!',
		}),
	},
} satisfies Dictionary;

export default userJobsContent;
