import { type Dictionary, t } from 'intlayer';

const verificationModalContent = {
	key: 'verificationModal',
	content: {
		verificationTitle: t({
			ru: 'Подтверждение email',
			en: 'Email verification',
			he: 'אימות אימייל',
			ar: 'تأكيد البريد الإلكتروني',
			uk: 'Підтвердження email',
		}),
		verificationSent: t({
			ru: 'Код отправлен',
			en: 'Code sent',
			he: 'הקוד נשלח',
			ar: 'تم إرسال الرمز',
			uk: 'Код надіслано',
		}),
		verificationSentTo: t({
			ru: 'Код подтверждения отправлен на',
			en: 'Verification code sent to',
			he: 'קוד אימות נשלח ל',
			ar: 'تم إرسال رمز التحقق إلى',
			uk: 'Код підтвердження надіслано на',
		}),
		verificationDescription: t({
			ru: 'Пожалуйста, введите код подтверждения, который мы отправили на ваш email',
			en: 'Please enter the verification code we sent to your email',
			he: 'אנא הזן את קוד האימות ששלחנו לכתובת האימייל שלך',
			ar: 'يرجى إدخال رمز التحقق الذي أرسلناه إلى بريدك الإلكتروني',
			uk: 'Будь ласка, введіть код підтвердження, який ми надіслали на ваш email',
		}),
		verificationCodeLabel: t({
			ru: 'Код подтверждения',
			en: 'Verification code',
			he: 'קוד אימות',
			ar: 'رمز التحقق',
			uk: 'Код підтвердження',
		}),
		verificationCodePlaceholder: t({
			ru: 'Введите код',
			en: 'Enter code',
			he: 'הזן קוד',
			ar: 'أدخل الرمز',
			uk: 'Введіть код',
		}),
		verificationTimeLeft: t({
			ru: 'Время до истечения',
			en: 'Time left',
			he: 'זמן נותר',
			ar: 'الوقت المتبقي',
			uk: 'Час до закінчення',
		}),
		verificationResendWait: t({
			ru: 'Повторная отправка через',
			en: 'Resend in',
			he: 'שלח שוב בעוד',
			ar: 'إعادة الإرسال خلال',
			uk: 'Повторне надсилання через',
		}),
		verificationVerify: t({
			ru: 'Подтвердить',
			en: 'Verify',
			he: 'אמת',
			ar: 'تحقق',
			uk: 'Підтвердити',
		}),
		verificationResend: t({
			ru: 'Отправить повторно',
			en: 'Resend',
			he: 'שלח שוב',
			ar: 'إعادة الإرسال',
			uk: 'Надіслати повторно',
		}),
		verificationVerifying: t({
			ru: 'Подтверждение...',
			en: 'Verifying...',
			he: 'מאמת...',
			ar: 'جاري التحقق...',
			uk: 'Підтвердження...',
		}),
		verificationCodeRequired: t({
			ru: 'Пожалуйста, введите код подтверждения',
			en: 'Please enter verification code',
			he: 'אנא הזן קוד אימות',
			ar: 'يرجى إدخال رمز التحقق',
			uk: 'Будь ласка, введіть код підтвердження',
		}),
		verificationSuccess: t({
			ru: 'Email успешно подтвержден! Вы подписаны на рассылку.',
			en: 'Email successfully verified! You are subscribed to the newsletter.',
			he: 'האימייל אומת בהצלחה! אתה רשום לניוזלטר.',
			ar: 'تم تأكيد البريد الإلكتروني بنجاح! أنت مشترك في النشرة الإخبارية.',
			uk: 'Email успішно підтверджено! Ви підписані на розсилку.',
		}),
		verificationError: t({
			ru: 'Ошибка при подтверждении кода',
			en: 'Error verifying code',
			he: 'שגיאה באימות הקוד',
			ar: 'خطأ في التحقق من الرمز',
			uk: 'Помилка при підтвердженні коду',
		}),
		verificationCodeResent: t({
			ru: 'Код отправлен повторно',
			en: 'Code resent',
			he: 'הקוד נשלח שוב',
			ar: 'تم إعادة إرسال الرمز',
			uk: 'Код надіслано повторно',
		}),
		resendError: t({
			ru: 'Ошибка повторной отправки',
			en: 'Resend error',
			he: 'שגיאת שליחה חוזרת',
			ar: 'خطأ في إعادة الإرسال',
			uk: 'Помилка повторного надсилання',
		}),
		verificationCodeExpired: t({
			ru: 'Код подтверждения истек',
			en: 'Verification code expired',
			he: 'קוד האימות פג תוקף',
			ar: 'انتهت صلاحية رمز التحقق',
			uk: 'Код підтвердження закінчився',
		}),
		cancel: t({
			ru: 'Отмена',
			en: 'Cancel',
			he: 'ביטול',
			ar: 'إلغاء',
			uk: 'Скасувати',
		}),
	},
} satisfies Dictionary;

export default verificationModalContent;
