services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: worknow-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/worknow
      # Add other env vars or use .env file
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: worknow-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worknow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 