import OpenAI from 'openai';
import pkg from '@prisma/client';

const { PrismaClient } = pkg;

const prisma = new PrismaClient();

// Initialize OpenAI client
const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

/**
 * AI-Powered Job Title Generation Service
 * Uses OpenAI to analyze job descriptions and generate accurate, professional titles
 */
class AIJobTitleService {
    
    /**
     * Generate job title using AI analysis
     * @param {string} description - Job description
     * @param {Object} context - Additional context (city, salary, etc.)
     * @returns {Promise<Object>} Generated title with confidence and analysis
     */
    static async generateAITitle(description, context = {}) {
        try {
            if (!process.env.OPENAI_API_KEY) {
                console.warn('⚠️ OpenAI API key not found. Using fallback method.');
                return this.fallbackTitleGeneration(description);
            }

            const prompt = this.buildPrompt(description, context);
            
            const completion = await openai.chat.completions.create({
                model: "gpt-3.5-turbo",
                messages: [
                    {
                        role: "system",
                        content: `You are an expert job title generator for the Israeli job market. 
                        Your task is to analyze job descriptions and generate concise, professional job titles in Russian.
                        
                        Requirements:
                        - Generate titles in Russian language
                        - Keep titles short and professional (max 5-7 words)
                        - Use specific job titles, not generic ones
                        - Consider the job location, requirements, and industry
                        - Avoid including salary, contact info, or extra details in the title
                        
                        Common job categories in Israel:
                        - Уборщик (Cleaner)
                        - Повар (Cook)
                        - Официант (Waiter)
                        - Грузчик (Loader)
                        - Водитель (Driver)
                        - Продавец-консультант (Sales Consultant)
                        - Кассир (Cashier)
                        - Строитель (Construction Worker)
                        - Электрик (Electrician)
                        - Сантехник (Plumber)
                        - Маляр (Painter)
                        - Курьер (Courier)
                        - Программист (Programmer)
                        - Сиделка (Caregiver)
                        - Няня (Nanny)
                        - Охранник (Security Guard)
                        - Парикмахер (Hairdresser)
                        - Массажист (Masseur)
                        
                        Return only the job title, nothing else.`
                    },
                    {
                        role: "user",
                        content: prompt
                    }
                ],
                max_tokens: 50,
                temperature: 0.3,
            });

            const generatedTitle = completion.choices[0]?.message?.content?.trim();
            
            if (!generatedTitle) {
                throw new Error('No title generated by AI');
            }

            return {
                title: generatedTitle,
                confidence: this.calculateAIConfidence(generatedTitle, description),
                method: 'ai',
                analysis: {
                    hasSpecificKeywords: this.hasSpecificKeywords(description),
                    hasLocation: this.hasLocation(description),
                    hasSalary: this.hasSalary(description),
                    hasLanguageRequirement: this.hasLanguageRequirement(description),
                    hasExperienceRequirement: this.hasExperienceRequirement(description)
                }
            };

        } catch (error) {
            console.error('❌ AI title generation failed:', error.message);
            return this.fallbackTitleGeneration(description);
        }
    }

    /**
     * Build AI prompt for job title generation
     * @param {string} description - Job description
     * @param {Object} context - Additional context
     * @returns {string} Formatted prompt
     */
    static buildPrompt(description, context = {}) {
        let prompt = `Analyze this job description and generate a professional job title in Russian:\n\n`;
        prompt += `Job Description: ${description}\n\n`;
        
        if (context.city) {
            prompt += `Location: ${context.city}\n`;
        }
        if (context.salary) {
            prompt += `Salary: ${context.salary} шек/час\n`;
        }
        if (context.requirements) {
            prompt += `Requirements: ${context.requirements}\n`;
        }
        
        prompt += `\nGenerate a concise, professional job title in Russian:`;
        
        return prompt;
    }

    /**
     * Fallback title generation when AI is not available
     * @param {string} description - Job description
     * @returns {Object} Generated title with fallback method
     */
    static fallbackTitleGeneration(description) {
        const lowerDescription = description.toLowerCase();
        
        // Simple keyword-based title generation
        let title = "Общая вакансия";
        
        if (lowerDescription.includes('повар') || lowerDescription.includes('кухня')) {
            title = "Повар";
        } else if (lowerDescription.includes('уборщик') || lowerDescription.includes('уборка')) {
            title = "Уборщик";
        } else if (lowerDescription.includes('официант') || lowerDescription.includes('ресторан')) {
            title = "Официант";
        } else if (lowerDescription.includes('грузчик') || lowerDescription.includes('склад')) {
            title = "Грузчик";
        } else if (lowerDescription.includes('водитель') || lowerDescription.includes('доставка')) {
            title = "Водитель";
        } else if (lowerDescription.includes('продавец') || lowerDescription.includes('магазин')) {
            title = "Продавец-консультант";
        } else if (lowerDescription.includes('кассир') || lowerDescription.includes('касса')) {
            title = "Кассир";
        } else if (lowerDescription.includes('строитель') || lowerDescription.includes('строительство')) {
            title = "Строитель";
        } else if (lowerDescription.includes('электрик')) {
            title = "Электрик";
        } else if (lowerDescription.includes('сантехник')) {
            title = "Сантехник";
        } else if (lowerDescription.includes('маляр')) {
            title = "Маляр";
        } else if (lowerDescription.includes('курьер')) {
            title = "Курьер";
        } else if (lowerDescription.includes('программист')) {
            title = "Программист";
        } else if (lowerDescription.includes('сиделка')) {
            title = "Сиделка";
        } else if (lowerDescription.includes('няня')) {
            title = "Няня";
        } else if (lowerDescription.includes('охранник')) {
            title = "Охранник";
        } else if (lowerDescription.includes('парикмахер')) {
            title = "Парикмахер";
        } else if (lowerDescription.includes('массажист')) {
            title = "Массажист";
        }
        
        return {
            title: title,
            confidence: 0.6, // Lower confidence for rule-based method
            method: 'rule-based',
            analysis: {
                hasSpecificKeywords: this.hasSpecificKeywords(description),
                hasLocation: this.hasLocation(description),
                hasSalary: this.hasSalary(description),
                hasLanguageRequirement: this.hasLanguageRequirement(description),
                hasExperienceRequirement: this.hasExperienceRequirement(description)
            }
        };
    }

    /**
     * Calculate confidence score for AI-generated title
     * @param {string} title - Generated title
     * @param {string} description - Original description
     * @returns {number} Confidence score (0-1)
     */
    static calculateAIConfidence(title, description) {
        if (!title || !description) return 0;
        
        const lowerTitle = title.toLowerCase();
        const lowerDescription = description.toLowerCase();
        
        // Check if title keywords appear in description
        const titleWords = lowerTitle.split(' ').filter(word => word.length > 2);
        const matchingWords = titleWords.filter(word => lowerDescription.includes(word));
        
        // Calculate basic confidence
        let confidence = matchingWords.length / Math.max(titleWords.length, 1);
        
        // Boost confidence for AI-generated titles
        confidence += 0.2;
        
        // Reduce confidence for generic titles
        if (lowerTitle.includes('общая') || lowerTitle.includes('работник')) {
            confidence -= 0.3;
        }
        
        return Math.min(Math.max(confidence, 0), 1);
    }

    /**
     * Batch generate titles for multiple jobs
     * @param {Array} jobs - Array of job objects
     * @returns {Promise<Array>} Array of jobs with AI-generated titles
     */
    static async batchGenerateAITitles(jobs) {
        console.log(`🤖 Starting AI-powered title generation for ${jobs.length} jobs...`);
        
        const results = [];
        let successCount = 0;
        let errorCount = 0;
        
        for (const job of jobs) {
            try {
                const context = {
                    city: job.city?.name,
                    salary: job.salary,
                    requirements: this.extractRequirements(job.description)
                };
                
                const titleData = await this.generateAITitle(job.description, context);
                
                results.push({
                    ...job,
                    title: titleData.title,
                    titleConfidence: titleData.confidence,
                    titleMethod: titleData.method,
                    titleAnalysis: titleData.analysis
                });
                
                successCount++;
                
                // Log progress every 10 jobs
                if (successCount % 10 === 0) {
                    console.log(`✅ Processed ${successCount}/${jobs.length} jobs`);
                }
                
                // Add small delay to avoid rate limiting
                await new Promise(resolve => setTimeout(resolve, 100));
                
            } catch (error) {
                console.error(`❌ Failed to generate title for job ${job.id}:`, error.message);
                errorCount++;
                
                // Use fallback for failed jobs
                const fallbackData = this.fallbackTitleGeneration(job.description);
                results.push({
                    ...job,
                    title: fallbackData.title,
                    titleConfidence: fallbackData.confidence,
                    titleMethod: 'fallback',
                    titleAnalysis: fallbackData.analysis
                });
            }
        }
        
        console.log(`\n📊 AI Title Generation Summary:`);
        console.log(`   Total jobs: ${jobs.length}`);
        console.log(`   Successfully processed: ${successCount}`);
        console.log(`   Errors (using fallback): ${errorCount}`);
        
        return results;
    }

    /**
     * Extract requirements from job description
     * @param {string} description - Job description
     * @returns {string} Extracted requirements
     */
    static extractRequirements(description) {
        const requirementPatterns = [
            /требуется\s+(.+?)(?=\n|$)/i,
            /требования?\s*:\s*(.+?)(?=\n|$)/i,
            /обязательно\s+(.+?)(?=\n|$)/i
        ];
        
        for (const pattern of requirementPatterns) {
            const match = description.match(pattern);
            if (match) {
                return match[1].trim();
            }
        }
        
        return '';
    }

    /**
     * Check if description has specific job keywords
     * @param {string} description - Job description
     * @returns {boolean}
     */
    static hasSpecificKeywords(description) {
        const specificKeywords = [
            'повар', 'официант', 'грузчик', 'водитель', 'продавец', 
            'кассир', 'уборщик', 'строитель', 'электрик', 'сантехник',
            'маляр', 'курьер', 'программист', 'сиделка', 'няня'
        ];
        
        return specificKeywords.some(keyword => 
            description.toLowerCase().includes(keyword)
        );
    }

    /**
     * Check if description mentions a location
     * @param {string} description - Job description
     * @returns {boolean}
     */
    static hasLocation(description) {
        const locationPatterns = [
            /в\s+([а-яё]+(?:\s+[а-яё]+)*)/i,
            /на\s+([а-яё]+(?:\s+[а-яё]+)*)/i
        ];
        
        return locationPatterns.some(pattern => pattern.test(description));
    }

    /**
     * Check if description mentions salary
     * @param {string} description - Job description
     * @returns {boolean}
     */
    static hasSalary(description) {
        const salaryPattern = /(\d+)\s*(?:шек|₪|ILS)/i;
        return salaryPattern.test(description);
    }

    /**
     * Check if description has language requirements
     * @param {string} description - Job description
     * @returns {boolean}
     */
    static hasLanguageRequirement(description) {
        const languageKeywords = ['иврит', 'ивритом', 'английский', 'английским', 'русский', 'русским'];
        return languageKeywords.some(keyword => 
            description.toLowerCase().includes(keyword)
        );
    }

    /**
     * Check if description mentions experience requirements
     * @param {string} description - Job description
     * @returns {boolean}
     */
    static hasExperienceRequirement(description) {
        const experienceKeywords = ['опыт', 'опытный', 'опыт работы'];
        return experienceKeywords.some(keyword => 
            description.toLowerCase().includes(keyword)
        );
    }

    /**
     * Update existing jobs in database with AI-generated titles
     * @returns {Promise<Object>} Update statistics
     */
    static async updateDatabaseWithAITitles() {
        console.log("🤖 Updating database with AI-generated titles...\n");
        
        try {
            const jobs = await prisma.job.findMany({
                include: {
                    city: true,
                    category: true
                }
            });
            
            console.log(`📊 Found ${jobs.length} jobs to update\n`);
            
            let updatedCount = 0;
            let skippedCount = 0;
            let errorCount = 0;
            
            for (const job of jobs) {
                try {
                    const context = {
                        city: job.city?.name,
                        salary: job.salary,
                        requirements: this.extractRequirements(job.description)
                    };
                    
                    const titleData = await this.generateAITitle(job.description, context);
                    
                    // Only update if the new title is better
                    if (titleData.confidence > 0.7 && titleData.title !== job.title) {
                        await prisma.job.update({
                            where: { id: job.id },
                            data: { title: titleData.title }
                        });
                        
                        console.log(`✅ Updated: "${job.title}" → "${titleData.title}" (${titleData.method})`);
                        updatedCount++;
                    } else {
                        console.log(`⏭️  Skipping "${job.title}" - confidence: ${titleData.confidence.toFixed(2)}`);
                        skippedCount++;
                    }
                    
                    // Add delay to avoid rate limiting
                    await new Promise(resolve => setTimeout(resolve, 200));
                    
                } catch (error) {
                    console.error(`❌ Failed to update job ${job.id}:`, error.message);
                    errorCount++;
                }
            }
            
            console.log(`\n📈 AI Update Summary:`);
            console.log(`   Total jobs processed: ${jobs.length}`);
            console.log(`   Jobs updated: ${updatedCount}`);
            console.log(`   Jobs skipped: ${skippedCount}`);
            console.log(`   Errors: ${errorCount}`);
            
            return {
                total: jobs.length,
                updated: updatedCount,
                skipped: skippedCount,
                errors: errorCount
            };
            
        } catch (error) {
            console.error('❌ Error updating database with AI titles:', error);
            throw error;
        }
    }
}

export default AIJobTitleService; 