name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile.dev --tag worknow-dev:$(date +%s)
    - name: Test the Docker image
      run: docker run --rm worknow-dev:$(date +%s) --version || echo "Docker image built successfully"
